import autopy

START_BUTTON_TXT = "Start"
STOP_BUTTON_TXT = "Stop"
WINDOW_NAME = "NoTouch"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
CURSOR_SMOOTHENING = 12
CAM_WIDTH, CAM_HEIGHT = 1280, 720
SCREEN_WIDTH, SCREEN_HEIGHT = autopy.screen.size()
INDEX_FINGER_ID = 8
MIDDLE_FINGER_ID = 12
RECTANGLE_FRAME = 1
